[package]
name = "bin2dec"
version = "1.0.0"
edition = "2021"
authors = ["João Dias <joaodias@noctus.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18" }
